[package]
name = "redscript-ide"
version = "0.1.0"
edition = "2021"

[dependencies]
lspower = "1.5"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "5.4"
ropey = "1.5"

[dependencies.redscript]
git = "https://github.com/jac3km4/redscript"
package = "redscript"
features = ["arc"]
rev = "f5334c6"

[dependencies.redscript-compiler]
git = "https://github.com/jac3km4/redscript"
package = "redscript-compiler"
rev = "f5334c6"
