[package]
name = "redscript-ide"
version = "0.1.6"
rust-version = "1.69"
edition = "2021"
license = "MIT"

[dependencies]
lspower = "1"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "5"
ropey = "1"
toml = "0.8"

[dependencies.redscript]
git = "https://github.com/jac3km4/redscript"
package = "redscript"
features = ["arc"]
rev = "0c64ff2"

[dependencies.redscript-compiler]
git = "https://github.com/jac3km4/redscript"
package = "redscript-compiler"
rev = "0c64ff2"

[workspace.metadata.release]
pre-release-commit-message = "chore: release {{version}}"
publish = false

[profile.release]
lto = "thin"
