[package]
name = "redscript-ide"
version = "0.1.0"
edition = "2021"

[dependencies]
lspower = "1.1"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "4.0"
ropey = "1.3"

[dependencies.redscript]
git = "https://github.com/jac3km4/redscript"
package = "redscript"
features = ["arc"]
rev = "v0.4.1"

[dependencies.redscript-compiler]
git = "https://github.com/jac3km4/redscript"
package = "redscript-compiler"
rev = "v0.4.1"
