[package]
name = "redscript-ide"
version = "0.1.2"
rust-version = "1.69"
edition = "2021"
license = "MIT"

[dependencies]
lspower = "1"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dashmap = "5"
ropey = "1"
toml = "0.7"

[dependencies.redscript]
git = "https://github.com/jac3km4/redscript"
package = "redscript"
features = ["arc"]
rev = "v0.5.14"

[dependencies.redscript-compiler]
git = "https://github.com/jac3km4/redscript"
package = "redscript-compiler"
rev = "v0.5.14"

[profile.release]
lto = "thin"
