on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      artifact:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-${{ inputs.os }}
      - run: cargo build --release
      - name: Rename binary to differentiate between OS
        if: ${{ inputs.os != 'windows-latest' }}
        run: mv ./target/release/redscript-ide ${{ inputs.artifact }}
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/${{ inputs.artifact }}
          name: artifact-${{ inputs.os }}
