name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  CARGO_INCREMENTAL: 0 # Incremental not supported by our caching
  CARGO_TERM_COLOR: always # GH action logs support terminal colors
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # New format as of 2023-03-09

jobs:
  lint:
    name: Run clippy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy -- -Dwarnings

  build:
    name: Build an artifact
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          path: target/release/redscript-ide.exe
