name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_INCREMENTAL: 0 # Incremental not supported by our caching
  CARGO_TERM_COLOR: always # GH action logs supports terminal colors
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # New format as of 2023-03-09

jobs:
  publish:
    name: Build, release, and upload artifacts
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: redscript-ide
      - run: cargo build --release
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{  github.ref_name }} --generate-notes $(Resolve-Path -Relative -Path ./target/release/redscript-ide.exe)
