name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_INCREMENTAL: 0 # Incremental not supported by our caching
  CARGO_TERM_COLOR: always # GH action logs supports terminal colors
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # New format as of 2023-03-09

jobs:
  prepare:
    name: Build and upload a release artifact for ${{ matrix.name }}
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-14
          - macos-latest
          - ubuntu-latest
        include:
          - os: windows-latest
            name: Windows
            artifact: redscript-ide.exe
          - os: macos-14
            name: MacOS Silicon
            artifact: redscript-ide-macos-silicon
          - os: macos-latest
            name: MacOS Intel
            artifact: redscript-ide-macos-intel
          - os: ubuntu-latest
            name: Linux
            artifact: redscript-ide-linux
    with:
      os: ${{ matrix.os }}
      artifact: ${{ matrix.artifact }}
  publish:
    name: Release artifacts
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{  github.ref_name }} --generate-notes $(Resolve-Path -Relative -Path ./binaries/*)
